version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: '08:00'
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
