setup:
	docker compose run --rm bolt npm install
	docker compose run --rm server create_db
	docker compose run --rm server ./manage.py users create_root --org default --password password admin@example.com 'Test Admin'
	docker compose run --rm server ./manage.py ds new --type pg --options '{"dbname": "postgres", "host": "postgres", "password": "postgres", "port": 5432, "sslmode": "prefer", "user": "postgres"}' 'redash DB'
sample_query_and_dashboard:
	curl -X POST "http://localhost:5001/api/queries" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"name": "query test", "description": null, "query": "select * from events", "is_draft": false, "data_source_id": 1}'
	curl -X POST "http://localhost:5001/api/queries/1" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"is_draft": false}'
	curl -X POST "http://localhost:5001/api/queries/1/results" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}"
	curl -X POST "http://localhost:5001/api/visualizations" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"query_id": 1, "type": "CHART", "name": "Chart", "description": "", "options": {"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "xAxis": {"type": "-", "labels": {"enabled": true}}, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"action": "x", "id": "y", "user_id": "series"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm"}}'
	curl -X POST "http://localhost:5001/api/visualizations" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"query_id": 1, "type": "COUNTER", "name": "Counter", "description": "", "options": {"counterLabel": "イベント", "counterColName": "action", "rowNumber": 1, "targetRowNumber": null, "stringDecimal": 0, "stringDecChar": ".", "stringThouSep": ",", "tooltipFormat": "0,0.000", "targetColName": "id", "countRow": true, "formatTargetValue": true, "stringSuffix": " Events", "stringPrefix": ""}}'
	curl -X POST "http://localhost:5001/api/dashboards" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"name": "Sample Dashboard"}'
	curl -X POST "http://localhost:5001/api/dashboards/1" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"is_draft": false}'
	curl -X POST "http://localhost:5001/api/widgets" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"options": {"parameterMappings": {},"isHidden": false,"position": {"autoHeight": false,"sizeX": 3,"sizeY": 8,"minSizeX": 1,"maxSizeX": 6,"minSizeY": 5,"maxSizeY": 1000,"col": 0,"row": 0}},"text": "","width": 1,"dashboard_id": 1,"visualization_id": 2}'
	curl -X POST "http://localhost:5001/api/widgets" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}" -d '{"options": {"parameterMappings": {},"isHidden": false,"position": {"autoHeight": false,"sizeX": 2,"sizeY": 5,"minSizeX": 1,"maxSizeX": 6,"minSizeY": 1,"maxSizeY": 1000,"col": 3,"row": 0}},"text": "","width": 1,"dashboard_id": 1,"visualization_id": 3}'
	curl -X POST "http://localhost:5001/api/dashboards/1/share" -H "Accept: application/json" -H "Authorization: Key ${REDASH_API_KEY}"
